apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "signet.fullname" . }}-pipeline
  labels:
    {{- include "signet.labels" . | nindent 4 }}
data:
  pipeline.py: |
{{ .Values.pipeline | indent 4 }}
